name: Docker Build & Export

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t smenycz-payout-calculator .

      - name: Save image to tarball
        run: docker save smenycz-payout-calculator -o smenycz-payout-calculator.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: smenycz-payout-calculator.tar
